### PR TITLE
Fixes, code "modernization", noexcept, and a new test 

### PR DESCRIPTION
**Pull request by vittorioromeo**
The implementation/semantics seem fine to me so far.

I've made some minor changes, added noexcept where appropriate, and tested out `ring_view<T>` on an "un-typed" array of `T`-aligned bytes.

### CODE REVIEW

**Comment by vittorioromeo** [comment]
Before moving forward, here are some thoughts/things to do:
- Add appropriate conditional `noexcept` clauses on the remaining methods.
- Reason about the value-"semanticness" of `ring_view`. (Should it be a regular type? Semiregular?)
- Design the implementation in such a way that allows `ring_view` to be adapted to non-contiguous containers in the future. (It's not a very appropriate use case, but there is no reason it shouldn't work with non-contiguous containers.)
- Some sort of way of making `ring_view` thread-safe without requiring an additional class?
- Is there any good use case where non-destructive semantics for `pop_front` would be preferred?

That's pretty much it for now. 
Nice work. :) 
Looking forward to hear your thoughts

**Comment by Quuxplusone** [comment]
I'll definitely pull in the `noexcept` and `using` changes (edit: done). The `foo<>::type -> foo_t<>` change would make the code fail to compile on my platform of choice, so I won't take that. I'm not a fan of the `wrap()` refactor either, on purely stylistic grounds.

I would expect `ring_view` to have the same "value-semanticness" as `array_view`, i.e., it's an object with "non-owning view" semantics.

Re your points 2 and 5: Today I'm wondering whether `ring_view` should do construction and destruction _at all_, or whether it should just take an array of `T` and use move-assignment for _everything_. That would actually be the easiest-to-reason-about semantics. Also, I think my current construct-and-destruct implementation "leaks" a bunch of constructed `T` objects when you destroy the view.

IMO thread-safety is _not_ the container's concern, and calling a member function on `ring_view` shouldn't introduce a synchronization point any more than calling a member function on `vector`. If you want thread-safety, slap a mutex around it.

**Comment by vittorioromeo** [comment]
Out of curiosity, what compiler/standard library are you using that does not support the `_t` type aliases?

---

I liked the `wrap` refactor as it binds the second argument of the binary modulus operator to `capacity`, therefore objectively reducing code repetition.

---

Regarding construction and destruction, which in my opinion is the most important issue: I think the approach we need to take is being **as general as possible**. 

If we can implement the current destructive semantics in a non-destructive implementation of `ring_view` using proxy classes or something similar, then the default `ring_view` implementation should be non-destructive.

If we can implement non-destructive semantics in a destructive implementation _(the current one)_ using, again, some sort of user-defined proxy type, then the default semantics should be destructive.

Regarding the current implementation, I think we just need a `~ring_view()` destructor that walks over the remaining elements, explicitly destroying them.

I need to put some thought into it, though. 
Looking forward to hear your thoughts about this issue.

---

I agree with you on the thread-safety issue.

**Comment by Quuxplusone** [comment]
> Regarding the current implementation, I think we just need a `~ring_view()` destructor that walks over the remaining elements, explicitly destroying them.

I think it's less recoverable than that.

```
std::vector<Foo> vec(100);  // 100 elements
ring_view<Foo>(vec.begin(), vec.end());  // take all the elements and destroy them
assert(vec.size() == 100);
// what's in the vector now? all its elements were destroyed by the ring_view!
```

Basically, if `ring_view` is going to be non-owning, then it shouldn't be messing with the lifetimes of the pointed-to objects. You can't destroy something you don't own! So that's why I'm now coming around to the opinion that `pop` should be non-destructive and `push` should _always_ be implemented as assignment — we lose the ability to store non-assignable objects, and we lose the ability to use a `ring_view<SomeSmartPtr<T>>` as an owning queue, but we gain sanity.

**Comment by vittorioromeo** [comment]
You're correct - the current destructive semantics are not viable. 

`pop()` should return by reference then, and `push()` should implemented as an assignment. Not sure if a `pop_move()` operation would be useful/safe.

Implementing a owning `ring_view` of `SomeSmartPtr` is a separate issue in my opinion - it should be implemented in a separate class (something similar to what I said during the meeting), that encapsulates both an **owning** storage and a `ring_view`, with destructive semantics and that exposes an interface that will do the right thing. 

We should try implementing something like that ourselves to take notice of possible design considerations.

**Comment by Quuxplusone** [comment]
Take a look at master circa 5606a33a19b5bd39884fa193b3f6088377eb4532 and see what you think of this completely new (and much simpler) assignment-based `ring_view`.

My main complaint with it now is that if we implement `fixed_ring` as "ring_view+array", then `fixed_ring<int>` becomes not-trivially-movable (because it contains internal pointers). This isn't fatal (because I imagine ring-buffers don't get moved around very much) but it is still a Bad Thing in that it implies that there's still room below `ring_view` for people to write their own more efficient ring-buffer implementations.

**Comment by vittorioromeo** [comment]
It's definitely a bad thing if a `fixed_ring` implemented in terms of `ring_view` is not as efficient as an hand-written one - I guess that doing that is not the correct thing, then.

I think having a more generic `ring_base` would be the best approach here, but I think its implementation would be pretty much the same as `ring_view`.

``` cpp
template<typename Container, typename Popper>
class ring_base;

template<typename T, typename Popper>
using ring_view = ring_base<T*, Popper>;

template<typename T, std::size_t Capacity, typename Popper>
using fixed_ring = ring_base<std::array<T, Capacity>, Popper>;
```

I think something like the above pseudocode could work fine.

**Pull request closed without merging**
